import React from 'react'
import ReactDOM from 'react-dom/client';
import './styles.css'
import { App } from './App'


/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

// Find all widget divs
const widgetDivs = document.querySelectorAll('.sepinaco-circularcarousel-webcomponent, #sepinaco-circularcarousel-webcomponent');

// Inject our React App into each class
widgetDivs.forEach(div => {
  const root = ReactDOM.createRoot(div);

  // get data-items attribute ==================
  const itemsString = div?.dataset?.items;
  const items = JSON.parse(itemsString);
  // Convert String "[0,0,0]" => Array [0,0,0]
  items.forEach(item => {
    item.position = JSON.parse(item.position);
    item.rotation = JSON.parse(item.rotation);
  });

  // get data-debug attribute ==================
  const debugString = div?.dataset?.debug;
  const debug = debugString === "true";

  // get data-radius attribute ==================
  const radiusString = div?.dataset?.radius;
  const radius = parseFloat(radiusString);

  // get data-radiusbanner attribute ==================
  const radiusBannerString = div?.dataset?.radiusbanner;
  const radiusBanner = parseFloat(radiusBannerString);

  // get data-radiusbanner attribute ==================
  const imageBanner = div?.dataset?.imagebanner;

  // Show logs if debug is true ==================
  console.log("Sepinaco Gallery WebComponent Debug mode: ", debug);
  if(debug) {
    console.log({itemsString});
    console.log({items});
    console.log({radius});
    console.log({radiusBanner});
    console.log({imageBanner});
  }

  root.render(
    <React.StrictMode>
      <App items={items} radius={radius} radiusBanner={radiusBanner} imageBanner={imageBanner} />
    </React.StrictMode>
  );
});
